# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Self-Driving-Car Developer Client' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Self-Driving-Car Developer Client
# pod 'RBSManager'
pod 'Starscream'
pod 'ObjectMapper'

end
